"""Initial migration

Revision ID: a56fb98041a0
Revises: 
Create Date: 2025-02-02 21:05:05.321067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56fb98041a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('power', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heroes_id'), 'heroes', ['id'], unique=False)
    op.create_index(op.f('ix_heroes_name'), 'heroes', ['name'], unique=False)
    op.create_index(op.f('ix_heroes_power'), 'heroes', ['power'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heroes_power'), table_name='heroes')
    op.drop_index(op.f('ix_heroes_name'), table_name='heroes')
    op.drop_index(op.f('ix_heroes_id'), table_name='heroes')
    op.drop_table('heroes')
    # ### end Alembic commands ###
